name: Update GitHub Profile

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:       # allows manual run

permissions:
  contents: write          # ✅ allow workflow to push changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.plugin.isocalendar.fullyear.svg   # ✅ save directly to root
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Ghulam-Ali-Bughio
          outputs: |
            github-snake.svg
            github-snake-dark.svg?palette=github-dark   # ✅ saved to root

      # ✅ Checkout repo again to restore .git folder before committing
      - name: Checkout repository again
        uses: actions/checkout@v3

      - name: Commit and Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Ghulam Ali
          author_email: ghulam-ali-bughio@users.noreply.github.com
          message: "🔄 Auto update metrics and snake [skip ci]"
